# Generated by Django 5.2 on 2025-11-16 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmarked_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
