# Generated by Django 5.2 on 2025-11-16 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_bookmarked_by_delete_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
